version: "3"
services:
  db:
    image: postgres:14
    container_name: bull_db
    restart: unless-stopped
    env_file: .env
    ports:
      - "${DATABASE_PORT:?DATABASE_PORT env var is missing on .env file}:5432"
    environment:
      POSTGRES_DB: ${DATABASE_NAME:?DATABASE_NAME env var is missing on .env file}
      POSTGRES_USER: ${DATABASE_USERNAME:?DATABASE_USERNAME env var is missing on .env file}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:?DATABASE_PASSWORD env var is missing on .env file}
    volumes:
      - pg-data:/var/lib/postgresql/data
volumes:
  pg-data:
  node_modules:
